[build]
  publish = "."

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Content-Type = "image/webp"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Content-Type = "image/x-icon"
