backend:
  name: git-gateway
  branch: main
  publish_mode: simple
  commit_messages:
    create: 'Content: create {{collection}} "{{slug}}"'
    update: 'Content: update {{collection}} "{{slug}}"'
    delete: 'Content: delete {{collection}} "{{slug}}"'
    uploadMedia: 'Media: upload {{path}}'
    deleteMedia: 'Media: delete {{path}}'

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "home"
    label: "Home Page"
    files:
      - name: "youtube_video"
        label: "YouTube Video URL"
        file: "content/home/youtube-video.md"
        fields:
          - {label: "YouTube Video URL", name: "youtube_url", widget: "string", default: "https://www.youtube.com/embed/4B3gF9HZRSI"}
      
      - name: "logo"
        label: "Website Logo"
        file: "content/home/logo.md"
        fields:
          - {label: "Logo Image", name: "logo_image", widget: "image", hint: "This logo will be used in the header and on the main page"}

  - name: "tickets"
    label: "Tickets Page"
    files:
      - name: "ticketshop"
        label: "Ticketshop URL"
        file: "content/tickets/ticketshop.md"
        fields:
          - {label: "Ticketshop Iframe URL", name: "ticketshop_url", widget: "string", hint: "The iframe URL for the ticketshop (e.g., EventSquare store URL)"}
      
      - name: "hero_section"
        label: "Hero Section"
        file: "content/tickets/hero-section.md"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string", default: "KOOP JE TICKETS", hint: "Main title in the hero section"}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "string", default: "Vedettweekend 2025", hint: "Subtitle below the main title"}
          - {label: "Hero Description", name: "hero_description", widget: "text", default: "Be there or be square! Koop hier je tickets voor het grootste feest van het jaar.", hint: "Description text in the hero section"}
          - {label: "Hero Button Text", name: "hero_button_text", widget: "string", default: "KOOP TICKETS", hint: "Text on the main call-to-action button"}

  - name: "featured_artists"
    label: "Featured Artists"
    folder: "content/featured-artists"
    create: false
    slug: "artist-{{name}}"
    fields:
      - {label: "Artist Name", name: "name", widget: "string"}
      - {label: "Date Badge", name: "dateBadge", widget: "string", hint: "e.g., VR 25 OKT, ZA 26 OKT"}
      - {label: "Artist Image", name: "image", widget: "image", hint: "Single image for both desktop and mobile"}
      - {label: "Title", name: "title", widget: "string", default: "CHECK IT OUT:"}
      - {label: "DJ Name", name: "djName", widget: "string", hint: "Full DJ/Artist name to display"}
      - {label: "Website URL", name: "websiteUrl", widget: "string", hint: "URL to redirect to when card is clicked"}
      - {label: "Website Icon", name: "websiteIcon", widget: "string", default: "fas fa-link", hint: "Font Awesome icon class"}
      - {label: "Active", name: "active", widget: "boolean", default: true}

  - name: "featured_sponsors"
    label: "Featured Sponsors"
    files:
      - name: "sponsors_list"
        label: "Featured Sponsors List"
        file: "content/home/featured-sponsors.md"
        fields:
          - {label: "Sponsors", name: "sponsors", widget: "list", fields: [
              {label: "Alt Text", name: "altText", widget: "string", hint: "Alternative text for accessibility"},
              {label: "Sponsor Image", name: "image", widget: "image", hint: "Sponsor logo image"},
              {label: "Website URL", name: "websiteUrl", widget: "string", hint: "URL to redirect to when sponsor is clicked"},
              {label: "Active", name: "active", widget: "boolean", default: true, hint: "Show/hide this sponsor"}
            ]}

  - name: "footer_sponsors"
    label: "Footer Sponsors"
    folder: "content/footer-sponsors"
    create: false
    slug: "footer-sponsor-{{name}}"
    fields:
      - {label: "Sponsor Name", name: "name", widget: "string", hint: "e.g., Footer Sponsor 1, Footer Sponsor 2, etc."}
      - {label: "Sponsor Image", name: "image", widget: "image", hint: "Sponsor logo image"}
      - {label: "Website URL", name: "websiteUrl", widget: "string", hint: "URL to redirect to when sponsor is clicked"}
      - {label: "Alt Text", name: "altText", widget: "string", hint: "Alternative text for accessibility"}
      - {label: "Active", name: "active", widget: "boolean", default: true}

  - name: "lineup"
    label: "Line-up Page"
    files:
      - name: "hero_section"
        label: "Hero Section"
        file: "content/lineup/hero-section.md"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string", default: "LINE-UP", hint: "Main title in the hero section"}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "string", default: "Vedettweekend 2025", hint: "Subtitle below the main title"}
          - {label: "Hero Description", name: "hero_description", widget: "text", default: "Ontdek de line-up van dit jaar", hint: "Description text in the hero section"}
      
      - name: "friday_timeline"
        label: "Friday Timeline"
        file: "content/lineup/friday-timeline.md"
        fields:
          - {label: "Day Title", name: "day_title", widget: "string", default: "VRIJDAG 25 OKTOBER", hint: "Title for Friday timeline"}
          - {label: "Timeline Items", name: "timeline_items", widget: "list", fields: [
              {label: "Time", name: "time", widget: "string", hint: "e.g., 20:00 - 21:00"},
              {label: "Image", name: "image", widget: "image", hint: "Artist/Event image"},
              {label: "Title", name: "title", widget: "string", hint: "Artist/Event name"},
              {label: "Subtext", name: "subtext", widget: "text", hint: "Description or additional info"},
              {label: "URL", name: "url", widget: "string", hint: "Link when clicked"},
              {label: "Active", name: "active", widget: "boolean", default: true, hint: "Show/hide this timeline item"}
            ]}
      
      - name: "saturday_timeline"
        label: "Saturday Timeline"
        file: "content/lineup/saturday-timeline.md"
        fields:
          - {label: "Day Title", name: "day_title", widget: "string", default: "ZATERDAG 26 OKTOBER", hint: "Title for Saturday timeline"}
          - {label: "Timeline Items", name: "timeline_items", widget: "list", fields: [
              {label: "Time", name: "time", widget: "string", hint: "e.g., 20:00 - 21:00"},
              {label: "Image", name: "image", widget: "image", hint: "Artist/Event image"},
              {label: "Title", name: "title", widget: "string", hint: "Artist/Event name"},
              {label: "Subtext", name: "subtext", widget: "text", hint: "Description or additional info"},
              {label: "URL", name: "url", widget: "string", hint: "Link when clicked"},
              {label: "Active", name: "active", widget: "boolean", default: true, hint: "Show/hide this timeline item"}
            ]}
