backend:
  name: github
  repo: TomoowTomoow/vedettweekend
  branch: main
  auth_type: implicit

media_folder: "img"
public_folder: "/img"

collections:
  - name: "featured_artists"
    label: "Featured Artists"
    folder: "content/featured-artists"
    create: true
    fields:
      - {label: "Artist Name", name: "name", widget: "string"}
      - {label: "Date Badge", name: "dateBadge", widget: "string"}
      - {label: "Artist Image", name: "imageDesktop", widget: "image"}
      - {label: "DJ Name", name: "djName", widget: "string"}
      - {label: "Website URL", name: "websiteUrl", widget: "string"}
      - {label: "Order", name: "order", widget: "number", default: 1}
      - {label: "Active", name: "active", widget: "boolean", default: true}
