backend:
  name: github
  repo: vedettweekend/vedettweekend  # your repo
  branch: main                        # branch to commit changes
  auth_scope: "repo"

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "site_settings"
    label: "Site Settings"
    files:
      - name: "youtube_video"
        label: "YouTube Video URL"
        file: "content/site-settings/youtube-video.md"
        fields:
          - {label: "YouTube Video URL", name: "youtube_url", widget: "string", default: "https://www.youtube.com/embed/4B3gF9HZRSI"}
