backend:
  name: auth0
  domain: dev-2sqbvsqp2p8q4qyh.eu.auth0.com   # Your Auth0 domain
  client_id: 2H7b1aPpWLSRj9Ch8MjO9vwlZZH11dsN  # Your Auth0 client ID
  repo: vedettweekend/vedettweekend             # Your GitHub repo
  branch: main                                 # Branch to commit content to

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "site_settings"
    label: "Site Settings"
    files:
      - name: "youtube_video"
        label: "YouTube Video URL"
        file: "content/site-settings/youtube-video.md"
        fields:
          - label: "YouTube Video URL"
            name: "youtube_url"
            widget: "string"
            default: "https://www.youtube.com/embed/4B3gF9HZRSI"
