backend:
  name: git-gateway
  branch: main
  publish_mode: simple
  commit_messages:
    create: 'Content: create {{collection}} "{{slug}}"'
    update: 'Content: update {{collection}} "{{slug}}"'
    delete: 'Content: delete {{collection}} "{{slug}}"'
    uploadMedia: 'Media: upload {{path}}'
    deleteMedia: 'Media: delete {{path}}'

# Enable team collaboration
local_backend: false

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "site_settings"
    label: "Site Settings"
    files:
      - name: "youtube_video"
        label: "YouTube Video URL"
        file: "content/site-settings/youtube-video.md"
        fields:
          - {label: "YouTube Video URL", name: "youtube_url", widget: "string", default: "https://www.youtube.com/embed/4B3gF9HZRSI"}
