name: Auto Deploy to Netlify

on:
  push:
    branches: [ main ]
    paths:
      - 'content/**'
      - 'admin/**'
      - '*.html'
      - 'styles/**'
      - 'script-new.js'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Deploy
        run: |
          echo "Content changed, triggering Netlify deployment..."
          # This will trigger Netlify to rebuild and deploy
